EleutherAI/gpt-neox

configs/gpt3_small.json
requirements.txt

* Removing Triton from `requirements.txt` and letting deepspeed install it itself solves that issue
* Validation is currently not working. Removed `validate_every` from configs.

GPT-3 Small Works

---

gpt_neox/gpt_neox.py

because the mask is now added rather than used as a boolean fill, a max negative value for the mask may lead to overflow. decrease by factor of 2

make mask value smaller by factor of 2

---

gpt_neox/gpt_neox.py

unties classifier weights from token embeddings after learning latest T5 switched to this scheme

untie classifier weights by default

---

gpt_neox/gpt_neox.py
train.py

@StellaAthena  i was totally wrong sorry, lol https://github.com/EleutherAI/gpt-neox/issues/55

implement gradient checkpointing

---

configs/gpt3_small.json

Small change so `config/gpt3_small.json` works

Batch size needs to be specified

---

configs/deepspeed_zero1.json
configs/gpt3_small.json
gpt_neox/datasets.py
gpt_neox/gpt_neox.py
scripts/train_gpt3small_pipeline.sh
train_enwik8_pipeline.py
train_pipeline.py

Fix pipeline training scripts.
Some fixes are *literally in the deepspeed library* so setup will need to install our deepspeed fork https://github.com/EleutherAI/DeepSpeed to properly work.

Fix train pipeline

---

Dockerfile
deploy_k8s.sh
install_deepspeed.sh

From @StellaAthena:
> 1. Store the hostfile in /job/hostfile so that the code automatically finds it and we don't need to provide it as an argument.
> 2. Install DeeperSpeed instead of DeepSpeed
> 3. The script lands you in ~/app/, which contains the contents of the GPT-NeoX repository. Would it be possible to have the GPT-NeoX repo be one layer deeper, so that it drops you in ~/app/ which contains the directory gpt-neox? That would be very pleasant but isn't necessary.
Addresses 1 & 2, fixes XY behind 3

Miscellaneous docker QoL improvements

---

.github/workflows/docker_build.yaml

Remove layer caching

---

README.md
megatron/arguments.py
megatron/checkpointing.py
megatron/data/dataset_utils.py
megatron/data/gpt2_dataset.py
megatron/model/__init__.py
megatron/model/gpt2_model.py
megatron/model/language_model.py
megatron/model/transformer.py
megatron/model/utils.py
megatron/mpu/initialize.py
megatron/mpu/layers.py
megatron/tokenizer/gpt2_tokenization.py
megatron/tokenizer/tokenizer.py
megatron/training.py
pretrain_gpt2.py
tasks/main.py

In accordance with the Megatron-LM terms of use and NVIDIA's license, I have added text to the header of each file that was originally authored by NVIDIA and subsequently modified by us. This test reads
I went with Biderman et al. because 1) updating every single file with new collaborators gets tiresome 2) we will fail to do it and 3) our license doesn't require headers on every file, so a minimal disclaimer to accord with the terms of NVIDIA's license is sufficient.
Hopefully nobody whose name comes before mine alphabetically will be added because going back and re-edit all the headers will be annoying.

Added copyright disclaimers

---

megatron/utils.py

Fixes:
```
Traceback (most recent call last):
File "./deepy.py", line 25, in <module>
from megatron.config_monster import ConfigMonster
File "/home/mchorse/gpt-neox/megatron/config_monster.py", line 10, in <module>
from megatron.utils import obtain_resource_pool
File "/home/mchorse/gpt-neox/megatron/utils.py", line 34, in <module>
from megatron.checkpointing import save_checkpoint
File "/home/mchorse/gpt-neox/megatron/checkpointing.py", line 35, in <module>
from megatron.utils import natural_sort
ImportError: cannot import name 'natural_sort' from partially initialized module 'megatron.utils' (most likely due to a circular import) (/h
```

HOTFIX BUG: circular import

---

Dockerfile
README.md
requirements.txt

**Objectives:**
- Clean up remaining remnants of overriding `python3` to `python3.8` in Ubuntu 18.09 LTS.
- Build with Open MPI 4.1 to follow the recommendation to use the latest stable version available.
- Switch to the latest stable NumPy release. (NumPy 1.20.1)
**Other Changes:**
- Remove mostly unneeded TensorFlow dependency from `requirements.txt`

Dockerfile and dependency improvements

---

megatron/arguments.py
megatron/model/gpt2_model.py

Adds an argument which allows you to control the method used to distribute model layers across pipeline stages. 
Choose from "parameters", which balances the number of parameters on each pipeline stage, "uniform", which naively balances the number of layers per stage, or "type:[regex]" (in our instance this will basically only be type:transformer), which balances layers whose class names match [regex]
ignore commit message, it's old lol

Add pipe-partition-method arg

---

megatron/arguments.py
megatron/model/gpt2_model.py
megatron/model/positional_embeddings.py
megatron/model/transformer.py

This should bring rotary up to almost the same speeds as learned embeddings, remove permutations and fix rotary + pipeline parallel, which wasn't working previously.
Also some mild reorganisation + added rotary pos emb 'base' as a configurable argument.
tests on a small model:
rotary old = pink, rotary new = purple, learned = orange

Rotary fixes

---

megatron/gradient_noise_scale/__init__.py
megatron/gradient_noise_scale/gradient_noise_scale.py
megatron/neox_arguments/megatron_args.py
megatron/training.py
requirements/requirements.txt

from `An Empirical Model of Large-Batch Training` - https://arxiv.org/abs/1812.06162
Should enable us to determine an ideal batch size / batch size schedule for training.
Requires you update your DeeperSpeed to commit hash https://github.com/EleutherAI/DeeperSpeed/commit/750f2140bf782cffeb578ce14a4e4cdb076f4326 or later.
Add `"log_gradient_noise_scale": true` to your config to test

Add Gradient Noise Scale measurement / logging

---

megatron/model/gpt2_model.py
megatron/model/utils.py

Shaden Smith (https://github.com/microsoft/DeepSpeed/pull/1014#pullrequestreview-648807573) pointed out that the `to_sequential` function was dropping gradient checkpointing support - this should fix that.

fix gradient checkpointing issue with `to_sequential`

---

.gitignore
README.md
configs/sparse.yml
megatron/model/gpt2_model.py
megatron/model/transformer.py
megatron/model/utils.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/utils.py
requirements/requirements.txt
tests/model/test_configs/test_sparse.yml
tests/model/test_model_instantiation.py
tests/neox_args/test_neoxargs_usage.py

- adds 'attention_config' param which inherits from neo
```
"""
Attention configuration for gpt-neox
The first item in the list specifies the attention type(s), and should be a list of strings. The second item 
specifies the number of times to repeat those attention types in the full list.
attention type choices:  [global, local (`sparse_fixed` with no global tokens), sparse_fixed, sparse_variable]
So a 12 layer network with only global attention could be specified like:
[[[`global`], 12]]
or a 12 layer network with alternating global / local like:
[[[`global`, `local`], 6]]
You can set a pattern to propagate across all layers like:
[[[`global`, `local`], "all"]]
If no attention_config is specified, this defaults to
[[[`global`], n_layers]]
"""
```
- adds a `sparsity_config` param - …

Refactor how we configure sparsity 

---

megatron/model/activations.py
megatron/model/transformer.py
megatron/neox_arguments/neox_args.py

Fixes geglu bias to be in accordance with https://arxiv.org/pdf/2002.05202.pdf (GELU(xW+b)⊗(xV+c))
and scales down the ff dims by 2/3 so we don't need to worry about parametrizing d_ff or balancing gelu vs. geglu experiments

scale d_ff for equal parameter count with geglu + fix geglu bias

---

megatron/training.py

Despite best efforts to fix checkpoint resuming, we've identified an additional bug that occurs when resuming a run with `gradient_accumulation_steps` set to a value above one. In particular, a training run that required continual restarts due to job time limits began producing the following loss trajectory:
Clearly, the run is not resuming in the exact same state as it left off, and small scale experiments isolated the issue the gas > 1 setting. The loss curves suggests that the model was revisiting data it had just previously encountered before the checkpoint. Indeed, upon resuming, the dataloader start iteration was not being fast forwarded in a manner that took into account the gradient accumulation steps, and this PR addresses this issue. This update appears to have restored the …

Fix gas checkpoint resuming

---

deepy.py
megatron/neox_arguments/arguments.py

Problem: neox args could not be instantiated from configs.yml saved with the checkpoint. Reason is the exponential notation which got saved as e.g. "1e10" (instead of "1.0e10"). On load of yaml this is interpreted as string. 
Solution: copy the original config files to the checkpoint directory. This way also potential comments are not lost. Files are copied upon instantiation of neox args in deepy.py
Assumption (unchanged): only of version of config is saved. A potential history of changed configs during training is not available in the checkpoint directory.

save original configs with checkpoint

---

megatron/data/blendable_dataset.py
megatron/data/data_utils.py
megatron/data/gpt2_dataset.py
megatron/data/helpers.cpp
megatron/initialize.py

blendable datasets were hanging when mp > 1 due to the barrier in blendable_dataset.py 
This should fix that, and also moves `compile_helpers` to initialize_megatron so it only runs once

fix blendable datasets + model parallel

---

README.md

this is purely based on the list of contributors available to me (screenshotted the small one). Perhaps there is another internal version I don't have access to, to which Alex, Preetham, Connor, Kip, and Phil Wang contribute, but at least according to my GitHub UI, they are not marked as contributors.
According to GitHub (as seen in #335):
This branch:

fix(readme): add missing contributors v2

---

megatron/text_generation_utils.py

if we hit this codepath (which happens when the first token is an eos token) then generated text is not defined.

Fix small error in text generation utils

---

megatron/neox_arguments/arguments.py

Problem: If load == save, the config save failes because we cannot copy files from the already deleted directory.
Solution: load config files into memory first, delete the directory, then save from memory.
Note: Overwriting may not be the best option as it is completely valid to instantiate with just some and not all of the config files. Simply overwriting with the files with the same name would result in left over config files, which are not part of the actual config any more. The simple option without comparing filenames and file contents is the deletion of the directory.

fix save config files to the load directory

---

eval_tasks/adaptor.py
eval_tasks/run.py
megatron/model/gpt2_model.py
megatron/model/positional_embeddings.py
megatron/model/transformer.py
megatron/model/utils.py
megatron/neox_arguments/neox_args.py
megatron/text_generation_utils.py
megatron/utils.py

- Adds generation tasks to lm_eval_harness adaptor
- Adds task parameters in neox args (`eval_tasks` - a list of tasks to evaluate on, & `eval_results_prefix` a prefix to the path where eval results will be saved)
- Makes it easier to switch between inference and train mode with neox model
- Adds stop tokens to text generation
- Fixes bug with rotary where caching would decrease generation quality

Eval harness update + Fix rotary bug

---

megatron/tokenizer/gpt2_tokenization.py

GPT2Tokenizer currently uses an unbounded cache (`GPT2Tokenizer.cache`) which will grow to extremely large sizes (a few million entries according to objgraph) when running `tools/preprocss_data.py`, leading to massive memory use, especially with many workers. 
Performance appears to be affected slightly.

Use lru_cache for GPT2Tokenizer.bpe

---

megatron/training.py

we were running way too many evaluation steps if the model is pipe parallel + has g.a.s on because of this line
```python
for _ in range(neox_args.gradient_accumulation_steps):
```
fixing this to 1 if the model is pipe parallel fixes the issue, as .eval_batch() already takes gradient accumulation steps into account.
```python
for _ in range(1 if neox_args.is_pipe_parallel else neox_args.gradient_accumulation_steps):
```
This also relates to [this issue](https://github.com/EleutherAI/gpt-neox/issues/377), and is probably the reason we were seeing a stopiteration error

Fix bug with number of evaluation steps

---

eval_tasks/__init__.py
eval_tasks/adaptor.py
megatron/training.py

addresses https://github.com/EleutherAI/gpt-neox/issues/366
The generation tasks aren't that fast - so best to stick to the log likelihood tasks (you can add them to the yaml with the "eval_tasks" parameter.
e.g
```yaml
"eval_tasks": ["lambada", "wikitext", "piqa"],
```

Run eval harness during training

---

megatron/model/__init__.py
megatron/model/gpt2_model.py
megatron/model/word_embeddings.py
megatron/neox_arguments/neox_args.py
megatron/training.py

- Adds a generalized `insert_layer` function to insert arbitrary layers in the model
- Uses it to add soft prompt tuning, but also could be used for other stuff (I'm thinking multimodal few shot training)
Should work in inference but haven't yet tested it.
We should be wary that soft prompt tuning / fine tuning will work better if we pad sequences up to max length, rather than packing them (which we do for pretraining).
I'll start working on a PR to simplify data loading + add an option to pad sequences, instead of pack.

Add soft prompt tuning

---

deepy.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/neox_arguments/template.py
requirements/requirements.txt

The deepspeed launcher args weren't being passed in in the right position. (launcher args should come before user script / args)
Also, using the --include / --exclude flags wasn't working properly (you can't specify those and num_gpus at the same time, weird stuff was happening with batch size calculations...)

fix launcher args being passed in and resource inclusion

---

eval_tasks/__init__.py
eval_tasks/adaptor.py
eval_tasks/eval_adapter.py
evaluate.py
megatron/model/gpt2_model.py
megatron/model/utils.py
megatron/mpu/layers.py
megatron/neox_arguments/arguments.py
megatron/utils.py

This fixes some problems relating to eval harness & model parallel models.
To summarize:
- logits weren't being gathered automatically, so with a model parallel size of 2, each machine only had vocab_size / 2 logits, which resulted in indexing errors.
- There was no straightforward way to toggle whether the logits were gathered or not, now there is (`model._set_parallel_output(value)`)
- When zero optimization was being used in a config, it would break at inference time. Fixed this by overriding the zero config when setting up for inference (https://github.com/EleutherAI/gpt-neox/compare/eval_harness_fix?expand=1#diff-b6ee2c1db780b46787ab3a576020f9a12695f3f5cb38ba8badcd5501960e5d22R409)
- There was no way to specify which tasks to run on the command line at runtime, you would have to …

Eval harness fix

---

megatron/checkpointing.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py

Saves config files in the global step directory instead of the neox_args.save directory. Discussion here: https://github.com/EleutherAI/gpt-neox/issues/459
Tested on small config with:
- mp 1, pp 1
- mp 2, pp 1
- mp1, pp 2
Question is how to get the config files from the load in deepy to the single processes. I opted for the hand-trough via neox args. Any other idea?

Fix checkpoint / config file management

---

eval_tasks/eval_adapter.py
megatron/checkpointing.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/text_generation_utils.py
megatron/training.py
megatron/utils.py

Adds the following:
- Data Parallelism to Eval Harness (need to test this a bit more thoroughly before merge)
- Adds the ability to specify a checkpoint path to run evaluation on with a command line argument, e.g:
```python
./deepy.py evaluate.py configs/tmp.yml --eval_tasks lambada pubmedqa --iteration 26000 --eval_results_prefix iteration_26000
```
- Adds the ability to specify a results prefix to save results to with a command line arg (see above)
Apologies, autoformatter made a lot of cosmetic changes too

Improve Eval Harness

---

requirements/requirements.txt

Hoping to help out with a minor housekeeping improvement:
Before this commit: 
pipenv install -r requirements/requirements.txt
...
ValueError: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/EleutherAI/lm-evaluation-harness.git#egg=<package-name>.
After: <success>

Update requirements.txt to work with pipenv

---

megatron/fused_kernels/scaled_masked_softmax.cpp
megatron/fused_kernels/scaled_masked_softmax.h
megatron/fused_kernels/scaled_masked_softmax_cuda.cu
megatron/fused_kernels/scaled_upper_triang_masked_softmax.h
megatron/fused_kernels/tests/test_fused_kernels.py
megatron/model/fused_softmax.py
megatron/model/gmlp.py
megatron/model/transformer.py
megatron/model/utils.py
tests/model/test_fused_kernels.py

We were getting bad eval results because the fused softmax kernel was innacurate for inputs with < 128 tokens.
This fix ports over the PR fixing this bug in megatron's nvidia-lm [here](https://github.com/NVIDIA/Megatron-LM/pull/133).
you can run 
```
python3 tests/model/test_fused_kernels.py
```
to run the tests to check everything is working ok.
Also tested a training run to make sure fused / non fused are equal: 
https://wandb.ai/eleutherai/fusion_test?workspace=user-sdtblck
As well as running lambada evaluation on the 20B model for fused / non fused / main branch before this pull request.
Fused:
```json
{
"lambada": {
"ppl": 3.674815951703958,
"ppl_stderr": 0.055201099118188275,
"acc": 0.7168639627401514,
"acc_stderr": 0.006276651586376826
}
}
```
Non-fused:
```json
{
"lambada": { …
```

Fix fused softmax kernel

---

generate.py
megatron/neox_arguments/neox_args.py
megatron/text_generation_utils.py

Generation with pipe + model parallel combined is currently broken due to the fact that deepspeed expects pipe parallel inputs to be broadcast from the zeroth model parallel rank, which is not yet implemented for layer pasts in particular. I'm working on a fix for that, but in the meantime, we should disallow this explicitly.

Hotfix to disallow generation with pipe + model parallel

---

README.md

As per issue #542:
* Added links to Torrent files for 20B model to the main README
* Specified download sizes to reduce the element of surprise, especially for the full weights

Add links for *.torrent files, specify download sizes

---

requirements/requirements.txt

Fix #589 by updating the DeeperSpeed requirement so that it tells pip to pull the repository with HTTPS instead of the Git protocol.

Update DeeperSpeed requirement to use HTTPS

---

.github/workflows/pull_request.yml

This PR adds a new update documentation task, which runs the `gen_docs` script, then commits the changes as the `github-actions` user, to all new PRs, ensuring that any changes to NeoX arguments are updated in the documentation.

Add documentation generation to CI

---

eval_tasks/eval_adapter.py
requirements/requirements.txt

Updates the `eval_adapter` to conform to the most recent lm-evaluation-harness `BaseLM` API. This allows for result caching during evaluation.
The following requirements in `requirements/requirements.txt` are bumped:
- `lm_eval==0.2.0`
- `lm_dataformat=0.0.20` This is a required dependency update for the former.

Update `eval_adapter` to conform to `lm_eval`'s `BaseLM`

---

megatron/text_generation_utils.py

Evaluation of stop_tokens fails when is a jagged array, because a jagged array cannot be converted to a Tensor. Thus all token groups must be the same length. This precludes stop_tokens being passed as, for example, `[[187,187],[535]]` which are both representations of `\n\n`.
A _jagged array_ is an array of arrays, a vector of vectors or a list of lists where each member of the outer list is another list which may be of a different length to any or all of its siblings. Another example of a jagged array is `[[1], [2,3], [4,5,6]]`
This change makes any usage of stop_tokens with a 1-dimensional list incompatible. LMK if maintaining compatibility is desired, and I'll make the requisite changes.

Load each stop_tokens token group into a Tensor

---

tests/neox_args/test_neoxargs_usage.py

The `test_neoxargs_usage` unit test was failing due to an unhandled edge case in the regular expression. I refactored the regex to handle it. Further context can be found in the closed issue. 
The configuration tests now all pass.
closes #641

Fix `test_neoxargs_usage` Unit Test

---

eval_tasks/eval_adapter.py

Replace the undefined use of _eos_token_id with _eot_token_id
in the eval_adapter.

Correct use of eot_token_id in eval_adapter

---

configs/neox_arguments.md
requirements/requirements.txt

We forked [https://github.com/EleutherAI/lm_dataformat](https://github.com/EleutherAI/lm_dataformat) so that we could continue maintaining it, but haven't updated the dependency in the main branch yet. this PR does that
The fork of lm_dataformat supports passing in a jsonl key correctly now.

Update `lm_dataformat` dependency

---

megatron/model/positional_embeddings.py

When using a model trained with AliBi positional embedding for inference, the cached matrix gets invalidated and recomputed after every generated token, which is very expensive. This PR offers an alternative where the matrix is grown exponentially when longer sequences are encountered, while using clipping to ensure it works for shorter sequences. This will have no effect at training time, where it will be initialized to, and remain unchanged at, the target sequence length as before.
It may also be worth setting a minimum target length, e.g. at 64 tokens, possibly making this depend on the max length specified in the text generation config. In any case, the below has been tested with an AliBi-trained model and allows fast generation after the initial few resizing steps.

Update AliBi matrix caching for dynamic sequence lengths

---

configs/neox_arguments.md
megatron/neox_arguments/arguments.py

This fixes the following error:
`[WARNING] [runner.py:178:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.`
the hostfile was sometimes not set properly when launching multinode training. This would result in the following traceback:
```Traceback (most recent call last):
File "/fsx/hailey/pythia/gpt-neox/train.py", line 30, in <module>
pretrain(neox_args=neox_args)
File "/fsx/hailey/pythia/gpt-neox/megatron/training.py", line 81, in pretrain
initialize_megatron(neox_args=neox_args)
File "/fsx/hailey/pythia/gpt-neox/megatron/initialize.py", line 75, in initialize_megatron
finish_mpu_init()
File "/fsx/hailey/pythia/gpt-neox/megatron/initialize.py", line 51, in finish_mpu_init
_initialize_distributed(neox_args=neox_args)
File …
```

Set hostfile in `get_deepspeed_main_args`

---

megatron/fused_kernels/setup.py

The pytorch based CUDA check in the setup script of the Megatron fused kernels would return False if a GPU is not available. A GPU is not required to build the fused kernels. This check prevents properly building NeoX image in CI.

Allow building of fused kernels without GPU

---

megatron/text_generation_utils.py

This PR fixes a bug which results in the interactive sample bombing out with:
ValueError: too many values to unpack (expected 4)

Fix interactive sample

---

.dockerignore
Dockerfile

This PR addresses a few pain points to make it easier to build & work with the Docker image

Docker tweaks

---

configs/neox_arguments.md
eval_tasks/eval_adapter.py
evaluate.py

The lm-eval-harness uses Linux wildcards to allow for the selection of multiple tasks sharing a prefix in their name at once, via passing `--tasks blimp_* ` to select all BLiMP tasks at once rather than manually.
This PR adds support for this pattern to the Eval-harness adapter, so that one can pass ` --eval_tasks blimp_* ` or `--eval_tasks hendrycks_* ` to run on all BLiMP or MMLU tasks without passing all task names individually, as a minor QoL fix.

Allow wildcard-style Eval Harness task selection

---

requirements/requirements.txt

when use `pip install -r requirements/requirements.txt` it raise error missing `=`

Fix Typo in requirements

---

configs/neox_arguments.md
tools/convert_to_hf.py

This PR makes the conversion to HF format raise an error if a model with a single layernorm and GPT-J residual setup is used, since it's not currently supported by HF.
cc @Quentin-Anthony @StellaAthena

Raise error in HF conversion script if using single tied layernorm with GPT-J residual

---

configs/neox_arguments.md
tools/convert_to_hf.py

Oops--the script should refuse to convert models when layernorms ARE shared, since what's supported by HF right now is 2 separate layernorms.
@StellaAthena

Fix shared LN error in HF conversion script

---

configs/1-3B.yml
configs/125M.yml
configs/13B.yml
configs/175B.yml
configs/19M.yml
configs/2-7B.yml
configs/20B.yml
configs/350M.yml
configs/49M.yml
configs/6-7B.yml
configs/760M.yml
configs/800M.yml
configs/bf16_125M.yml
configs/bnb_125M.yml
configs/gmlp_small.yml
configs/neox_arguments.md
configs/slurm_125M.yml

This PR addresses #749 and #748 . The example configs need patching to reflect the removal of the `save-interval` arg.
@StellaAthena @ShivanshuPurohit

`save-interval` -> `checkpoint-factor` in all example configs

---

README.md
configs/neox_arguments.md
configs/text_generation.yml
generate.py
megatron/model/transformer.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/text_generation_utils.py
megatron/training.py
tools/convert_to_hf.py

Available both for input-file and interactive modes, it rerolls the input request in the latter until it meets the stop sequence.
Especially useful for continuing indent-aware code and lists generation.
I tested it for both cases and it works as intended

Enable multiline prompts by setting a custom prompt end

---

configs/20B.yml

`gpt_j_tied=false` will cause 20B model generate gibberish results. This is reported [here](https://github.com/EleutherAI/gpt-neox/issues/745) and [here](https://github.com/EleutherAI/gpt-neox/issues/755).
The source of the problem is this [commit](https://github.com/EleutherAI/gpt-neox/commit/0accac618d70bd62de3965c037a7b2a36d07deb1).
To reproduce, run `./deepy.py generate.py ./configs/20B.yml`
"gpt_j_tied": false
```
{"context": "", "text": " de de general de general de2a1a\u00ada\u00ada\u00ada\u00ada\u00ada\u00ada\u00ado\u00ado\u00ado\u00ado\u00ado\u00ado\u00ado\u00ado\u00ado\u00ado3\u00ado\u00ado3\u00ado3\u00ado3\u00ado\u00ado\u00ado\u00ado\u00ado", "length": 64, "finished": false, "message": null, "duration_seconds": 4.648434400558472}
```
"gpt_j_tied": true
```
{"context": "", …
```

set gpt_j_tied to true so that 20B inference works again

---

configs/20B.yml
configs/neox_arguments.md
megatron/model/transformer.py

This PR makes it so that when `neox_args.gpt_j_tied = True`, the layernorms are tied to each other. When `neox_args.gpt_j_tied = False`, there are now 2 separate untied layernorms as intended.

Fix behavior of `gpt_j_tied` synced LayerNorms

---

requirements/requirements.txt

`lm-eval` was pined to `0.2.0`. Seems to be outdated because some tests can't be found (e.g. lambada_openai, lambada_standard)
Upgrade it to `0.3.0` solved the problem.

Update lm-eval version

---

configs/neox_arguments.md
megatron/training.py

In #737 I added functionality to specify arbitrary training steps at which a checkpoint should be saved, including step 0 of training.
There is a bug with the step 0 checkpointing currently. For some reason, `iteration = 0` was already set before that PR in the `pretrain()` function but never used. However, this leads the step 0 checkpointing to save a "step 0" checkpoint whenever training is resumed (if a step 0 checkpoint is asked for). 
This means that the supposed "step 0" checkpoint would be overwritten at each resumption of training. 
This PR fixes that issue. It doesn't affect any models we trained, luckily.
@Quentin-Anthony @StellaAthena

Bugfix for Iteration 0 checkpointing

---

megatron/data/indexed_dataset.py
tools/preprocess_data.py

This PR is trying to accelerate `preprocess_data.py`. There are mainly 2 optimizations:
- pass `numpy.ndarray` to `add_item` of `IndexDatasetBuilder` to avoid an immediate `tensor.numpy()`.
- use `np.cumsum` instead of a loop to calculate the pointer offsets.
Thank you for your time on reviewing this PR :)

Optimize data preprocessing by using numpy

---

configs/neox_arguments.md
eval_tasks/eval_adapter.py

When running the eval-harness via GPT-NeoX using more than 1 GPU, evals would fail by default unless setting `use_cache=False` with an error like the following:
```
File "/fsx/hailey/pythia/lm-evaluation-harness/lm_eval/evaluator.py", line 247, in evaluate
return func(*args, **kwargs)
File "/fsx/hailey/gpt-neox/eval_tasks/eval_adapter.py", line 394, in run_eval
results = evaluator.evaluate(
File "/fsx/hailey/pythia/lm-evaluation-harness/lm_eval/utils.py", line 161, in _wrapper
resps = getattr(lm, reqtype)([req.args for req in reqs])
File "/fsx/hailey/pythia/lm-evaluation-harness/lm_eval/base.py", line 820, in fn
results = evaluator.evaluate(
File "/fsx/hailey/pythia/lm-evaluation-harness/lm_eval/utils.py", line 161, in _wrapper
return fn(*args, **kwargs)
File …
```

Default `use_cache=False` in eval harness integration

---

Dockerfile

Removes redundant generation/use/deletion of password.txt by placing the password as a variable and running echo with the variable directly.
Previously, the text 'password' was echoed into password.txt, then read from it again, before the file would finally get deleted.

Remove need/use of password.txt

---

configs/neox_arguments.md
megatron/data/indexed_dataset.py

tested to be backwards-compatible to as old as numpy==1.18.0
https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

Remove deprecated numpy calls

---

megatron/data/data_utils.py

while `train-data-paths` just contains ONE path, get `ZeroDivisionError` here:
https://github.com/EleutherAI/gpt-neox/blob/192022f52b1df48e4e3138810adb22d9ff51d1ff/megatron/data/data_utils.py#L281

fix `ZeroDivisionError` while only one train data

---

configs/neox_arguments.md
megatron/tokenizer/tokenizer.py

Fixes the following error: 
```bash
../gpt-neox/megatron/tokenizer/tokenizer.py", line 355
try:
^
IndentationError: unexpected indent
```

fix unexpected indent error for conditional `tiktoken` import

---

megatron/neox_arguments/deepspeed_args.py

Missing end of comment
Avoid `SyntaxError: unterminated string literal (detected at line 218)`

Update deepspeed_args.py - Avoid SyntaxError: unterminated string literal (detected at line 218)

---

configs/neox_arguments.md
megatron/neox_arguments/deepspeed_args.py

Looks like I accidentally uncommented and committed a duplicate `no_ssh_check` arg in https://github.com/EleutherAI/gpt-neox/commit/e897c23e921101a3d84208f2717e0c462e8bd20a

Remove duplicate no_ssh_check arg

---

Dockerfile

```
$ ssh root@IP
Permission denied, please try again.
```
default config `#PermitRootLogin prohibit-password` should be replaced by `PermitRootLogin yes`

Fix ssh login

---

.github/workflows/cpu_ci.yml
.github/workflows/pull_request.yml

Changes made by this PR can be summarized as follows:
- Set the `cache` and `cache-dependency-path` argument to enable caching to speed up CI times.

feat(ci): add `pip` caching to CI

---

configs/neox_arguments.md
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/training.py

Cleans up a few gotchas:
- If the config doesn't specify all batch size params, our `calculate_derived` function failed due to an indentation mismatch
- Our error output `"Either train_batch_size or micro_batch_per_gpu needs to be provided"` doesn't reflect the actual config option to set, which should be `train_micro_batch_size_per_gpu`
- If `log_interval` or `optimizer` isn't set, neox fails cryptically. I added some error messages so that users know what's missing

Fix minor issues

---

configs/finetuning_configs/6-9B.yml
megatron/checkpointing.py

neox repo has problem to use "finetune" option (https://github.com/EleutherAI/gpt-neox/issues/767)
this option can reset hyperparams in optimizer/lr_scheduler but, doesn't set model parameters correctly
i you use finetune in main branch it doesn't sync module with optimizer params
To sync module with optimizer params, change just 1 params simply
```
checkpoint_name, state_dict = model.load_checkpoint(
neox_args.load,
load_optimizer_states=load_optim_and_scheduler,
load_lr_scheduler_states=load_optim_and_scheduler,
load_module_only=not load_optim_and_scheduler,
tag=tag,
)
```
i add one line code to use load_module_only option in deepspeed's load_checkpoint function
```
if load_module_only:
deepspeed_states = ['module']
if self.optimizer is not None and self.fp16_enabled(): …
```

[bug-fix] enable finetuning option(set optimizer params correctly)

---

Dockerfile
configs/neox_arguments.md

Removes password based login for root, this should fix the security issues we've been having.

remove password based login for root

---

configs/neox_arguments.md
megatron/neox_arguments/deepspeed_args.py
megatron/training.py

We currently pass the `--deepspeed_config` in 
https://github.com/EleutherAI/gpt-neox/blob/056e9caf23e04a2ee13b5066cb6b7bef5404aa33/megatron/neox_arguments/arguments.py#L546
but also pass the config in
https://github.com/EleutherAI/gpt-neox/blob/056e9caf23e04a2ee13b5066cb6b7bef5404aa33/megatron/training.py#L627
This used to be allowed by DS, but the latest version requires us to choose ([DS commit](https://github.com/microsoft/DeepSpeed/commit/47f9f13bd3236d426d558d61ef358b36191ef026) and [gpt-neox user facing this issue](https://github.com/EleutherAI/gpt-neox/issues/885)). Restricting to a single config passed is backwards-compatible and fixes this issue.
Further, DeepSpeed will automatically launch with `torch.dist` if a single node is used, and will disregard if a user requests `srun` …

Remove duplicate deepspeed config and allow forced multinode

---

configs/README.md
configs/bf16_125M.yml
configs/neox_arguments.md
megatron/training.py

As was pointed out in #939 , the documentation and example configs no longer match NeoX's behavior regarding bf16 training. This updates `configs/bf16_125M.yml` and `configs/README.md` to be in sync with current functionality.

Updates bf16 demo config and mixed precision docutmentation.

---

configs/neox_arguments.md
megatron/neox_arguments/arguments.py

This restores prior behavior of using serialized versions of the deepspeed and megatron configs as command line params passed to `deepy.py` and then to `training.py`. This allows each node and process to get the same configuration parameters in a cluster-agnostic way.

Return to broadcasting megatron and deepspeed configs as training.py arguments

---

tools/multinode_prepare_data.sh

I added a simple bash script for multi-node data preparation.
**Why is it needed**
Large amounts of data may require more processing than a single compute-node can provide within a reasonable amount of time.
Therefore, multi-node support would enable an easy and straightforward way to preprocess the data.
**How does it work**
A list of files containing the data is provided. These files a split up evenly across the different ranks of the multi-node setup. Each rank thus processes a chunk of the data.
**What needed to change?**
Nothing in the python code itself has changed. However, there is a bash-script now that can be called in your distributed setup of choice instead of `tools/preprocess_data.py`

added a simple script for multi-node data preparation.

---

configs/neox_arguments.md
megatron/data/data_utils.py
megatron/data/gpt2_dataset.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/training.py
megatron/utils.py
tools/preprocess_data_with_mask.py

As discussed with @haileyschoelkopf in DM, I'm cleaning up my personal fork and putting the major difference out here in case it is a useful feature. It allows to take an optional `label_data_paths` (which is assumed to be perfectly in sync with the training data). 
But if there is anything that does not fit with the current design or anything, feel free to close it though.
It was used when finetuning diff models, where a custom loss mask needs to be applied to the dataset. It is very controllable if I can do it on the dataset level and easy to double-check by poking into the generated masks.
I also used this in some experiments of finetuning pythia for text repairing. It works well.
- Without the argument `label_data_paths`, nothing should change. 
- With the argument, it will 
- also …

Adding the possibility of passing a label dataset

---

README.md
requirements/requirements-tensorboard.txt

requirements/requirements-tensorboard.txt
The following error was generated from a dependency on the tensorboard version specified in
By modifying the tensorboard version, it now works. 
tensorboard == 2.5.0 then the error occurs (The second error corresponds to)again and the version needs to be corrected!
Traceback (most recent call last):
File "train.py", line 20, in <module>
from megatron.training import pretrain
File "/home/tn/gptneox-test/gpt-neox/megatron/training.py", line 58, in <module>
from eval_tasks import run_eval_harness
File "/home/tn/gptneox-test/gpt-neox/eval_tasks/__init__.py", line 15, in <module>
from .eval_adapter import EvalHarnessAdapter, run_eval_harness
File "/home/tn/gptneox-test/gpt-neox/eval_tasks/eval_adapter.py", line 16, in <module>
import best_download
File …

Fix setup README and tensorboard version

---

megatron/tokenizer/train_tokenizer.py

For BPE tokenization, `tokenizer_type` argument should be a string instead of the list.

default tokenizer_type should be string

---

megatron/model/transformer.py

* Received "AttributeError: module 'torch' has no attribute 'concat'" on torch 1.8.1+cu111
* `torch.concat` is an alias for `torch.cat` and there are four other instances of `torch.cat `already being used in this file

Replaced all torch.concat with torch.cat

---

tools/preprocess_data.py

old log
```
Processed 521000 documents (24077.20811125894 docs/s, 5.05394863005669 MB/s).: : 520000it [00:21, 24642.85it/s] 
```
new log
```
Processed 521000 documents (24077.21 docs/s, 5.05 MB/s).: : 520000it [00:21, 24642.85it/s] 
```

format docs/s and MB/s

---

tools/merge20b.py

I've noticed that gpt-neox has moved towards addressing config items using `_` rather than `-` to separate words (see e.g. #928).
The old way is still used in one script, and it bugged me... and it also seems risky: This script modifies fields, so if they already exist with `_` as should be expected, it will not overwrite as intended, but add additional fields with `-`, causing clashes down the line.
According to my regex (`\[['"][a-zA-Z]+-[a-zA-Z-]+['"]\]`), this is the only remaining occurrence of hyphens addressing config items in the code.
Also, this is my first contribution to gpt-neox. I did not find the contribution guidelines and apologise in advance if I'm trampling all over them; I'd be grateful if you let me know if I am.

Turn remaining hyphens into underscores in merge20b.py

---

megatron/model/utils.py

Fix #854 
Error: `'SequentialWrapper' object has no attribute 'clear_cache'`

Fix Generation with Sequential Model

---

configs/llama/train_config.yml

Add training config for llama.
Llama finetuning  can be launched with
```sh
python ./deepy.py ./train.py ./configs/llama/7B.yml ./configs/llama/train_config.yml ./configs/local_setup.yml
```
If training from scratch, set `finetune=False` in `./configs/llama/train_config.yml`

add training config for llama

---

megatron/model/utils.py
megatron/training.py

This PR fix the following bug for generating with `pipe_parallel_size = 0`
set `pipe_parallel_size = 0`
```
$ python ./deepy.py generate.py -d configs 125M.yml local_setup.yml text_generation.yml
```
The following error occurres when generating with `pipe_parallel_size = 0`
```sh
is_pipe_parallel ................ False.......................default
pipe_parallel_size .............. 0...........................default
Traceback (most recent call last):
File "generate.py", line 91, in <module>
main()
File "generate.py", line 73, in main
generate_samples_interactive(
File "/workspace/gpt-neox/gpt-neox-dev-latest/megatron/text_generation_utils.py", line 782, in generate_samples_interactive
for (
File "/workspace/gpt-neox/gpt-neox-dev-latest/megatron/text_generation_utils.py", line 319, in …
```

Fix SequentialWrapper Generation (pipe_parallel_size = 0)

---

megatron/model/flash_attention.py
megatron/model/transformer.py
requirements/requirements-flashattention.txt

Integrated flash attention 2 (ver. 0.2.2 -> 2.2.1). Wall-clock performance improvement observed for 125M param model with seq length 4096 and batch size 128 running on 1 a10 GPU.

integrated flash attention 2

---

megatron/learning_rates.py

I found that the current linear decay scheduler is incorrect. When `self.num_iters` reached `self.end_iter`, the learning rate `lr` is not 0

Fixed final value of linear decay lr

---

.github/workflows/coverity_scan.yml
configs/neox_arguments.md

Generic boilerplate coverity scan workflow:
Downloads coverity build tool
Builds from project code
Uploads a build to scan queue

adding boilerplate coverity scan to submit to public analysis

---

configs/neox_arguments.md
megatron/neox_arguments/arguments.py
tools/datasets/README.md

As #995 pointed out, the labelled datasets created by the `preprocess_data_with_mask.py` script do not work when specifying training data with the `data_path` option. Documentation to that effect has been added, as well as a check in `arguments.py`

Add documentation about using labelled datasets

---

configs/neox_arguments.md
megatron/training.py

Failed to test previous PR for inference mode, this adds a check so that `setup_model_and_optimizer` works when there is no optimizer (e.g. when using it to initialize DeepSpeed for inference)

LR scheduler fix no longer breaks inference

---

configs/neox_arguments.md
megatron/neox_arguments/neox_args.py
megatron/optimizers.py
megatron/training.py
tests/model/test_model_instantiation.py
tests/model/test_model_train.py

Lion Optimizer

---

configs/neox_arguments.md
tools/datasets/corpora.py

Fixing path for `tools/datasets/preprocess_data.py`

Fix preprocess_data.py link

---

configs/neox_arguments.md
tools/ckpts/convert_hf_to_sequential.py

This PR fixes a few bugs encountered when attempting to convert from HF to NeoX checkpoint format, via the invocation of the script through `deepy.py` in the multi-GPU case. 
After fixing these, and using `"launcher": "slurm", "deepspeed_slurm": true` in the config file I passed, conversion works for this distributed case. The distributed case can be always used if desired, even on a single GPU, and whether or not MP/PP are > 1.

Edge-casing for multi-GPU HF-to-NeoX conversion

---

configs/neox_arguments.md
requirements/requirements.txt

This PR pins the version of the lm-evaluation-harness used for the integration for the time being, until v0.4.0 and up are both released and support is added to GPT-NeoX for them.

Pin version of `lm_eval`

---

megatron/neox_arguments/arguments.py

On some clusters, it appears that a script specifying `#SBATCH --ntasks_per_node` instead of `#SBATCH --ntasks` will fail to build the environment variable `os.environ["SLURM_NTASKS"]`. This leads to an error in `arguments.py`, due to accessing a non-existing key of `os.environ`. A simple fix is to note that NTASKS = NNODES x SLURM_NTASKS_PER_NODE and use the right handside if the `SLURM_NTASKS` key does not exist in `os.environ`.

fixed case when ntasks_per_node is used, leading to missing SLURM_NTASKS env var

---

tools/ckpts/convert_module_to_hf.py
tools/ckpts/convert_sequential_to_hf.py

When processing mlp.dense_4h_to_h.bias and attention.dense.bias, tp_ranks are not reflected, so strange results always appear when tp_ranks is greater than 1.
When changing the code, we confirmed that the hugging face model (model_parallel_size 4 was applied) was converted to a neox model using convert_hf_to_sequential.py and converted to a huggingface model using convert_sequential_to_hf.py, making it the same as the original model.

Fixing convert neox to huggingface bug

---

tests/neox_args/test_neoxargs_usage.py

Fixes #1025 
`test_neoxargs_usage` does a regex search for patterns of the form "args.*" and verifies that such used args are defined in `NeoXArgs`. In this case it picks up a false positive from 
https://github.com/EleutherAI/gpt-neox/blob/f214358baea68c1631e650e073371010b4b9b60e/megatron/neox_arguments/arguments.py#L938-L940

Resolve existing CPU unit test errors

---

configs/neox_arguments.md
requirements/requirements.txt

There is a bug in upstream DeepSpeed detailed [here](https://github.com/microsoft/DeepSpeed/issues/4781) that we didn't catch before synching with main. This pins the prior commit so the bug doesn't impact users.

Pins old DeeperSpeed until bug is fixed

---

configs/neox_arguments.md
megatron/model/transformer.py
megatron/neox_arguments/neox_args.py

Implementation for QK Normalization based on https://arxiv.org/abs/2302.05442
Part of the ablations used for sparse-gpt

Add QK Normalization

---

tools/datasets/corpora.py

Made this fix on my pythia-reproduction branch and it seemed like it should be ported forward

Fix openwebtext2 downloader

---

configs/neox_arguments.md
megatron/neox_arguments/arguments.py
megatron/neox_arguments/deepspeed_args.py

Pairs with https://github.com/EleutherAI/DeeperSpeed/pull/59 . 
This lets users pass a value for both `--account` and `--comment` to the SlurmLauncher's srun command.

Enable passing of `--account` to `srun` / SlurmLauncher

---

configs/1-3B.yml
configs/125M-json.yml
configs/125M.yml
configs/13B.yml
configs/175B.yml
configs/19M.yml
configs/2-7B.yml
configs/20B.yml
configs/350M.yml
configs/49M.yml
configs/6-7B.yml
configs/760M.yml
configs/800M.yml
configs/bf16_125M.yml
configs/bnb_125M.yml
configs/slurm_125M.yml
megatron/devutil.py
megatron/model/fused_layer_norm.py
megatron/model/norms.py
megatron/neox_arguments/neox_args.py
megatron/utils.py
tests/config/test_setup.yml
tests/test_configs/test_train_base.yml

- Add simple util for timings
- Add fused layernorm kernel from Megatron

fused layernorm

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
configs/neox_arguments.md
megatron/neox_arguments/arguments.py

Contributing Guide

---

configs/neox_arguments.md
megatron/training.py

1. Trigger `run_eval_harness` import only when `eval_tasks` is specified since this requires internet connection. (Times out on network-restricted clusters)
2. Add notes to the docs

Better run_eval_harness import

---

configs/neox_arguments.md
megatron/neox_arguments/neox_args.py
requirements/requirements.txt

We now have released v0.4.1 and v0.4.0 of lm-eval on PyPI.
This PR makes requirements.txt reflect that, instead of using the git repo (though users who want the newest code version can choose to install from the repo.)

Update lm_eval v0.4 to PyPI dependencies

---

configs/19M.yml
configs/49M.yml
configs/800M.yml
configs/neox_arguments.md
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/training.py
tests/config/test_setup.yml

per code being removed:
```gas: int = None
"""gradient_accumulation_steps"""  # TODO this is a duplicate, remove?
```
This is set in many configs and [never assigned from](https://github.com/search?q=repo%3AEleutherAI%2Fgpt-neox%20gas&type=code). Its continued existence in neox only encourages people to set ```gas```, which does apparently nothing, instead of setting ```gradient_accumulation_steps```, which is probably what they intended to do.
Pythia configs left alone because the source of truth for those configs is the pythia repo.

Remove gas (beano)

---

configs/gen_docs.py
configs/neox_arguments.md
megatron/neox_arguments/neox_args.py
megatron/training.py

I believe some of the profiling neox args had their names changed, which seems to be causing trouble when I try to run on the latest codebase commit:
```
Traceback (most recent call last):
File "/weka/hailey/mistral-support-neox/gpt-neox/train.py", line 34, in <module>
main()
File "/weka/hailey/mistral-support-neox/gpt-neox/train.py", line 30, in main
pretrain(neox_args=neox_args)
File "/weka/hailey/mistral-support-neox/gpt-neox/megatron/training.py", line 228, in pretrain
iteration = train(
File "/weka/hailey/mistral-support-neox/gpt-neox/megatron/training.py", line 884, in train
loss_dict, skipped_iter = train_step(
File "/weka/hailey/mistral-support-neox/gpt-neox/megatron/training.py", line 775, in train_step
neox_args.profiling
AttributeError: 'NeoXArgs' object has no attribute …
```

[Bug?] Fix profiling argument names

---

configs/mistral/7B.yml
configs/neox_arguments.md
megatron/model/transformer.py
megatron/neox_arguments/arguments.py

As raised by @malteos , Flash attention requires not 2.0.0+ but version 2.3.0+ to support sliding_window_width. However also, sliding-window attention is supported in the absence of Flash.
This PR changes the argument validation to 1) check for version 2.3.0 and 2) only perform this check if "flash" type attention is used. Also, it doesn't pass window_size kwarg when not required, meaning we'll never give the invalid kwarg to flash versions < 2.3.0 .

Improve argument validation for Flash-attn + SWA

---

Dockerfile
configs/neox_arguments.md
requirements/requirements-flashattention.txt

Swapped the raw cuda container for the ngc pytorch 24.02 container.
This one has OpenMPI, PyTorch and Apex already installed, so those setup steps can be removed.
`flash-attn` was recently hotfixed for that container version, so 2.5.6 is a hard requirement.
To validate the setups, I ran a few training steps of Pythia 14M on 8xA100 and a 22B model on 8xA100 and 8xH100 w/ TP8.
The apt and pip install lists and requirements files could be cleaned up. E.g. trition is already present and gets downgraded. I will leave it like this for now in order to keep this PR small.
For multi node tests I will have to adapt the launcher first.

Single node Pythia 14M training on ngc pytorch 24.02 container

---

configs/neox_arguments.md
megatron/mpu/mappings.py

No `torch.distributed` operation that would require a bf16 -> fp32 conversion is performed in the `_split` function, so it's safe to remove this.
Since `fp32_allreduce=True` is necessary for combining zero 1 & bf16, this should result in less memory allocation for common zero 1 + MP + PP use cases (saw ~10% drop on 125M model, albeit with batch size 4)

Remove unnecessary fp32/bf16 conversion

---

configs/neox_arguments.md
megatron/model/positional_embeddings.py
megatron/model/transformer.py
megatron/neox_arguments/neox_args.py
tools/ckpts/convert_neox_to_hf.py
tools/ckpts/convert_raw_llama_weights_to_neox.py

closes #1161 .
Makes the `inv_freq` rotary embedding buffer not saved in checkpoints, in keeping with NeoX, Mistral, and Llama in Huggingface post-4.36 .
Since this is a breaking change to saved checkpoints in GPT-NeoX which do store it, added a flag so people can turn it back on and load from the checkpoint.

Make rotary freqs buffer non-persistent

---

megatron/training.py
requirements/requirements.txt

Currently, if you try to use the following `optimizer` and `zero_optimizer` settings:
```yaml
"optimizer": {
"type": "Lion",
"params": {
"lr": 0.0006,
"betas": [0.9, 0.999],
}
},
"zero_optimization": {
"stage": 1,
"allgather_partitions": True,
"allgather_bucket_size": 500000000,
"overlap_comm": True,
"reduce_scatter": True,
"reduce_bucket_size": 500000000,
"contiguous_gradients": True,
},
```
You will encounter:
```shell
[2024-03-01 14:35:58,937] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = Lion
assert (
AssertionError: You are using an untested ZeRO Optimizer. Please add <"zero_allow_untested_optimizer": true> in the configuration file to use it.
[2024-03-01 14:35:58,937] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=Lion …
```

Support Lion with Zero Optimizer

---

configs/neox_arguments.md
requirements/requirements.txt

we no longer use best_download as of updating the lm-eval-harness integration, so removing it from requirements.

remove `best_download` as dependency

---

README.md
tools/datasets/README.md
tools/datasets/preprocess_data.py
tools/datasets/preprocess_data_with_mask.py

This PR aims to fix a minor typo in documentation of `preprocess_data.py` and `preprocess_data_with_mask.py`.

Fix documentation for --jsonl-keys argument of preprocess_data scripts

---

Dockerfile

Cleaning up the Dockerfile after the ngc pytorch switch (#1170):
- Eliminate already installed apt packages
- sparse attn requirement lead to a triton downgrade
- flash attn is already part of the ngc container (in another version that is compatible with TE)
The flash-attn change might be required for TE, see the [TE setup script](https://github.com/NVIDIA/TransformerEngine/blob/b459ccc93549c13797f884271904e019ad7fa3db/setup.py#L268). The following error from the docker log was indicating so, too. I am not 100% sure if the version upper limit is a technological requirement, or just a precaution. In any case this is now resolved, plus there's no need to build flash-attn.
```
#14 10.98 Installing collected packages: flash-attn
#14 10.98   Attempting uninstall: flash-attn
#14 10.98     Found …
```

Cleaner dockerfile: Remove already installed deps

---

megatron/model/transformer.py

When using kv cache and flash attention in conjunction, it's crucial to set the causal parameter of flash_varlen_qkv_fn to False. Failing to do so will lead to inaccurate results.

Resolve issues between kv_cache and flash attention.

---

configs/neox_arguments.md
megatron/model/transformer.py
megatron/neox_arguments/arguments.py

Since 2.4.0.post1, Flash-attn has supported alibi_slopes in its cuda kernels, removing the need for using the triton backend. This PR switches over to using the cuda flash functions rather than triton for compatible flash versions, but retains compatibility for Alibi + flash<2.4.0 via triton for now with a warning.
Future PRs could potentially add the updated Triton implementation from the triton repo which could be faster on H100s, as this is distinct from the triton impl. in the flash attention repo.

Switch to using Cuda Flash Attn for Alibi

---

configs/neox_arguments.md
megatron/model/gpt2_model.py
megatron/model/mamba/__init__.py
megatron/model/mamba/mamba.py
megatron/neox_arguments/arguments.py
tools/ckpts/convert_neox_to_mamba_ssm.py

This PR adds Mamba + TP support.
Loss curves comparing TP=2 to TP=1 with + without `mamba_inner_func_fusion`:
Versus when allreduce was missing with inner func fusion turned on:
Also tested that PP seems to work.

Mamba + Tensor Parallel Support

---

megatron/training.py

[ZeRO-3] Partitioned init with `deepspeed.zero.Init()`

---

megatron/fused_kernels/__init__.py
megatron/fused_kernels/scaled_masked_softmax_cuda.cu
megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu
megatron/initialize.py
tests/model/test_fused_kernels.py

This PR aims to enable JIT compilation for fused kernels on AMD GPUs, so that the same code will run on both AMD and NVIDIA GPUs. 
Previous `python setup.py install` method has issues with hipifying files, which results in ninja generating multiple rules for the same target. 
This will also make the extra fused kernel building instruction in the readme unnecessary. I will take care of the readme parts once this get approved
#954 
Reference: https://github.com/microsoft/Megatron-DeepSpeed/commit/b4d4a0e06577218a21abf18eb7d8088bb8ecaad3

[AMD] Supporting fused kernels build using JIT

---

README.md
configs/125M-dmoe.yml
megatron/data/helpers.cpp
megatron/model/megablocks_utils.py
megatron/model/transformer.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/training.py
tools/ckpts/convert_hf_to_sequential.py

This initial version focuses on getting megablocks integrated and working with DS parallelism. It makes megablocks experts work within the existing parallelism, which has the full degrees of freedom including expert, expert-data, and tensor-expert-data parallelism.
Tested on 8xA100 for convergence, expert balancing, and uncovered weight initialization issues (to be fixed later).
Design document and worklog that accompanied this project: https://yaaang.notion.site/gpt-neox-MoE-design-doc-cc8586eb53144a5987b63f510ced021c
In terms of where this fits larger arcs of work, next PRs (don't have permission to submit stacked PRs) are for:
- improved expert initialization like we discussed
- adding integration tests around this that automate the verification I was showing earlier around convergence …

Add megablocks dropless MoE

---

tools/ckpts/convert_neox_to_hf.py

In tools/ckpts/convert_neox_to_hf.py, for neox architecture the 'intermediate_size' argument is not explicitly set, so it defaults to 24576 from:
https://github.com/huggingface/transformers/blob/9fe3f585bb4ea29f209dc705d269fbe292e1128f/src/transformers/models/gpt_neox/configuration_gpt_neox.py#L48
Proposed solution: set intermediate-size to 4 * hidden-size.

Fix bug in tools/ckpts/convert_neox_to_hf.py for setting intermediate_size

---

tools/ckpts/convert_hf_to_sequential.py

Fixes the very high loss at start of training a split pythia/neox model
Matches it so that the summed biases [https://github.com/EleutherAI/gpt-neox/blob/main/tools/ckpts/convert_neox_to_hf.py#L520-L525](url) from the HF checkpoint are split appropriately in a tensor parallel case.
(For reference, magenta is pre-fix, blue is post-fix, grey is a 1.4b run without model parallelism for reference)

fix conversion of hf -> neox for pythia in model parallel

---

.github/workflows/pull_request.yml
megatron/data/helpers.cpp
megatron/model/norms.py
megatron/neox_arguments/arguments.py
tools/datasets/README.md
tools/datasets/preprocess_data_with_chat_template.py

Add a chat based preprocessing script, to support multiturn conversation finetuning

Add a chat data preprocessing script

---

megatron/model/init_functions.py

I think this is supposed to be referencing "Transformers without Tears: Improving the Normalization of Self-Attention" ( https://arxiv.org/abs/1910.05895) which was published in 2019 not 2010

Fix paper reference in init_functions.py

---

configs/neox_arguments.md
megatron/model/utils.py
megatron/training.py

Fix the all reduce gradient hook for LayerNorm, by moving hook registration for gradient all reduce for the LayerNorm parameters to after `deepspeed.initialize`. Update the gradient hook to sum in the LayerNorm gradient in the sequence dimension instead of average.
Test Plan
This PR does not fix the convergence issue, since the loss still ends up flat-lining around 7.5 for enwiki8. When printing out LayerNorm parameters, I observed that in the current `sequence_parallel=True` implementation, the LayerNorm weight parameters change much slower than when `sequence_parallel=False`.

Fix LayerNorm all reduce gradient hook

---

.github/workflows/.cpu_ci_on_pr.yml
.github/workflows/coverity_scan.yml
.github/workflows/cpu_ci.yml
.github/workflows/cpu_ci_dispatch.yml
.github/workflows/cpu_ci_on_pr.yml
.github/workflows/pull_request.yml
tests/README.md

This PR concerns replacing the run labels in the workflows to avoid disruptions to CI, as well as some updated documentation / comments for CI use:
- replacing self-hosted with ubuntu-22.04 in workflows
- updating documentation to address CI target change
- added guidance comments about storing / managing secrets for the Coverity scan submission workflow

Conversion for CI from self-hosted hardware

---

configs/neox_arguments.md
megatron/mpu/mappings.py

Improve the performance of sequence parallel gather, scatter, and reduce by using `reduce_scatter_tensor` and `all_gather_into_tensor` when possible.
WandB before: https://wandb.ai/brandony/neox/runs/wcim8pf6?nw=nwuserbrandony
WandB after: https://wandb.ai/brandony/neox/runs/gkaoomq5?nw=nwuserbrandony
From the plot, goes from 15.7e12 flops to 17.3e12 flops, with baseline at 18e12 flops.

Improve performance of sequence parallel gather, scatter, and reduce

---

README.md
configs/neox_arguments.md

I added new models that have come out trained with the GPT-NeoX library. The library itself is sufficiently well-used that simply listing all citing papers is rapidly becoming non-viable. I'm currently leaning towards providing a curated list of "exciting" papers? I haven't looked at other libraries to see what they do yet.

Add new cites

---

configs/mamba/mamba-1.4B.yml
configs/mamba/mamba-130M.yml
configs/mamba/mamba-2.8B.yml
configs/mamba/mamba-370M.yml
configs/mamba/mamba-790M.yml
megatron/model/mamba/mamba.py
megatron/neox_arguments/arguments.py

adds:
- some common configs to mamba configs so they can be ran easier.
- a fix to some mamba configs
- bypasses some checks in arguments.py
- an assertion error when mamba is missing packages instead of a warning message

mamba fixes and cleaning

---

megatron/data/data_utils.py
megatron/data/gpt2_dataset.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/training.py

- add different packing impl (Unpacked, packing until overflow), a bit naive but for SFT it shouldn't be an issue
- fix labels to also have valid/test implementations
- fix label masking in _get_batch to also include anything from get_ltor_masks_and_position_ids

SFT improvements (labeling fixes, different packing implementations)

---

configs/1-3B.yml
configs/llama/13B.yml
configs/llama/30B.yml
configs/llama/65B.yml
configs/llama/7B.yml
megatron/data/helpers.cpp
megatron/model/activations.py
megatron/model/gmlp.py
megatron/model/mamba/mamba.py
megatron/model/rwkv/v6/rwkv.py
megatron/model/transformer.py
megatron/neox_arguments/neox_args.py

The current implementation only allows to set `intermediate_size` for Llama models, but I would like to be capable to change the `intermediate_size` in GPT-NeoX models. 
I have tested this implementation under a quick training, inference and conversion and it seems that it doesn't give any bugs. I hope it helps!

Add `intermediate_size` to GPT-NeoX models

---

.pre-commit-config.yaml
configs/neox_arguments.md
megatron/model/fused_layer_norm.py
megatron/model/norms.py
megatron/model/transformer_engine.py
megatron/model/utils.py
megatron/neox_arguments/neox_args.py
requirements/requirements-transformerengine.txt
tests/README.md

Adds:
- Apex's rmsnorm
- TransformerEngine's rmsnorm and layernorm

LayerNorm Refactor

---

megatron/model/utils.py

Change the TE import to be properly conditional. I didn't catch it in https://github.com/EleutherAI/gpt-neox/pull/1269 since I had tested it with TE installed (oops!)
Refactored this function while I was around.
@aurelion-source -- FYI

TE Import Hotfix

---

megatron/text_generation_utils.py

Makes behavior observed in https://github.com/EleutherAI/gpt-neox/issues/1250 explicit.

Expand Docstring

---

megatron/mpu/mappings.py

Fixes a bug with sequence parallel training that negatively affects convergence when the model parallel group is a subset of the available.

Add model parallel group to reduce scatter

---

README.md
configs/local_setup_comet.yml
requirements/requirements-comet.txt

* Set minimum version of compatible Comet SDK
* Add Comet in the Readme where other logging integrations are mentioned
* Fix typo in Comet instructions and de-emphasize the Comet workspace, most users have a single Comet workspace and it's not needed to set it to start logging

Update Comet integration instructions

---

tools/datasets/preprocess_data_with_chat_template.py

since the mask is assumed to be causal, previously we were doing the reward value on the last token in the sequence, not the EOS token. Did not affect llama-3 models much, since the EOS token is double applied in this instance (the chat has an EOS token already), but would be potentially problematic for other models.

Fix off by 1 error on masked tokens for RM training

---

README.md
configs/local_setup_wandb.yml

1. Separate wandb config from `local_setup.yml` into `local_setup_wandb.yml`. Make `local_setup.yml` tensorboard-only
2. Update wording throughout README to reflect that we have more than wandb, and so that sections are more consistent.
@Lothiraldan -- FYI

Make monitors consistent

---

megatron/data/gpt2_dataset.py

There was a typo from https://github.com/EleutherAI/gpt-neox/pull/1244/files#diff-383134de6f3512484e20625419bd5fb6b1675a922f47aeb1a6bd3cff6185a754R126 that snuck in. 
Only showed up after several hundred iterations.
FYI -- @aurelion-source @dmahan93

Fix dataset bug

---

megatron/fused_kernels/type_shim.h
megatron/logging.py

adds accurate mamba flop calculations to gpt-neox

mamba flop calculations

---

megatron/neox_arguments/neox_args.py

Sometimes you cannot have git installed. This PR allow running gpt-neox in such environment.

Do not fail when git is not installed

---

README.md
configs/prof.yml
megatron/neox_arguments/neox_args.py

Improve readme descriptions and add sample profiling config

Improve Profiling Docs

---

megatron/training.py

Add's broadcasting of train_iters from rank 0 when dataloader is not present

hotfix for tp >= 2 and pp > 2 in autoitercount

---

megatron/training.py
post-training/README.md

-Add an assert to block dpo/kto/rm training when running pipeline parallel, as get_batch_pipe does not have the relevant logic yet
-Add assert when kto + train_micro_batch_size_per_gpu == 1 since kto needs a reference
-remove python post-training/llama_dpo_data.py as this file does not exist and is not nessesary to get the code running

Add additional asserts  and update post training readme

---

megatron/neox_arguments/arguments.py

When trying to run `./deepy.py train.py ...` I got the following error:
> `NameError: name 'ERROR' is not defined`
I tracked this down and found that we have a number of formatted logging prefixes with colors, but `ERROR` was missing. I added that (with the color red, same as for `FAIL`), sorted the prefixes alphabetically, and grouped them a bit for clearer organization. Tested and got an actual error message after the change.

Add ERROR logging prefix and sort the prefixes alphabetically

---

configs/llama/13B.yml
configs/llama/30B.yml
configs/llama/65B.yml
configs/llama/7B.yml
configs/llama/train_config.yml
configs/llama2/13B.yml
configs/llama2/70B.yml
configs/llama2/7B.yml
megatron/model/transformer.py

After the 'mlp_type' option was removed, the regular-type and the llama-type of MLP share the same implementation, and the "mlp_type" is now specified by whether the activation is gated or not.
However, this changes the meaning of the 'intermediate_size' option in llama configuration files. The code (megatron/model/transformer.py) now treats 'intermediate_size' as the size of the output tensor of the first linear layer in the MLP, which includes the first layer and the gated layer of llama-type MLP. This means that the code actually halves the 'intermediate_size' of llama-type MLP. Meanwhile, the code multiplies the 'intermediate_size' by (2/3), which means the actual 'intermediate_size' is only (1/3) of the intended size in the configuration file.
To fix this problem, I revised the llama …

fix 'intermediate_size' in Llama configuration files after the 'mlp_type' option was removed

---

README.md

In this issue Python 3.10 support was added https://github.com/EleutherAI/gpt-neox/pull/1122

Python 3.10 support

---

post-training/README.md

Quick documentation fix. 
In the documentation [post-training/README.md](https://github.com/EleutherAI/gpt-neox/blob/59a5236ddaf721890e3d6ef98fb8ca66c2266ce0/post-training/README.md), the base weights were converted from HF Llama: 
https://github.com/EleutherAI/gpt-neox/blob/59a5236ddaf721890e3d6ef98fb8ca66c2266ce0/post-training/README.md?plain=1#L6  
When converting fine-tuned weights from GPTNeoX format back to HF Llama, the `--architecture llama` flag seems to be required (otherwise the default value `"neox"` would be selected.) While specified for RM conversion, this flag is not included in the command for converting GPTNeoX SFT/DPO weights back to HF in this documentation.
https://github.com/EleutherAI/gpt-neox/blob/59a5236ddaf721890e3d6ef98fb8ca66c2266ce0/post-training/README.md?plai …

Fix documentation for converting SFT/DPO weights back to HF Llama

---

megatron/neox_arguments/arguments.py

https://github.com/EleutherAI/gpt-neox/issues/1305 Shows that you can set the bf16 config without setting the precision to bfloat16 and this causes an obscure crash. This should automatically set the precision when it's missing or throw crash with an assert if precision conflicts.

Add default bf16 precision setting when bf16 config option is set but precision is unset.

---

megatron/model/transformer.py
megatron/neox_arguments/arguments.py

Fixes https://github.com/EleutherAI/gpt-neox/issues/1324
also fixed a small formatting issue that snuck past the previous precommit.
Bad commit: https://github.com/EleutherAI/gpt-neox/pull/1309/commits/dc4b81fe0e5286b395a4a4a65163ba4f4afb98af#diff-46c4c76deb18adf1de8e0be6d4229baed5f1f0308e141479f5a993b3d83dd445

Fix if-clause

---

configs/eleutherai_cluster.yml
megatron/logging.py
megatron/neox_arguments/__init__.py
megatron/neox_arguments/arguments.py
megatron/neox_arguments/neox_args.py
megatron/utils.py

- Logs MFU/HFU if the user passes `neox_args.peak_theoretical_tflops`
- Log tokens_per_sec, iters_per_sec to wandb, comet, and tensorboard
- Add ability to manually specify wandb experiment name

Add Additional Logging Metrics

---

megatron/model/utils.py

Addresses #1316
Forward in SequentialWrapper is coded such that it always returns the logits and moe_loesses whether or not the model architecture is moe.
A flag is added to return moe losses if needed (default is False).

Make returning moe_losses optional in SequentialWrapper

---

megatron/model/transformer_engine.py

Resolves #1347 
- TE configures the activation function internally via the "activation" argument. Removed redundant manual activation logic.
- Cleaned up unnecessary dimension calculations. These are also performed internally by TE.
Tested for functionality and loss with TE v2.1.0

Resolve Transformer Engine SwiGLU Issue

---

megatron/model/transformer.py
tools/ckpts/convert_neox_to_hf.py

Resolves #1353
- Updates the conversion script to correctly map NeoX+TE model weights to HF without the need for a custom class.
- Removes the unused `post_attention_layernorm` layer when `TELayerNormMLP` is used.
The updated conversion script works for NeoX+TE models whether or not `post_attention_layernorm` was initialized. I removed this layer to make sure we avoid redundant memory allocation and unused parameter keys when using TE.
@Kyle1668 @Quentin-Anthony

NeoX+TE --> HF Conversion 

---

megatron/model/norms.py
tools/ckpts/convert_hf_llama_to_neox.py
tools/ckpts/convert_neox_to_hf.py

Resolves #1337 and #1342
- Following #1315, the GQA code no longer splits heads based on num_q_heads. This PR updates tools/ckpts/convert_hf_llama_to_neox.py to concatenate tp-partitioned q, k, and v weights without per-head splitting.
- The current RMSNorm implementation incorrectly adds epsilon to the RMS instead of the variance. Fix is the same as #1342, but ensures compatibility with partial RMSNorm.

Fix issues with Llama HF->NeoX conversion

---

tests/neox_args/test_neoxargs_commandline.py

Currently `test_neoxargs_commandline.py` contains two tests with same name `test_neoxargs_consume_deepy_args_with_config_dir`. This PR fixes the neoxargs consume without config dir test so it won't be silently ignored.

Fix neoxargs consume without config dir test
