configs/gpt3_small.json, gpt_neox/__init__.py, gpt_neox/downloader.py, gpt_neox/utils.py, train.py
Changes:
- download module for only downloading datasets
- adjusted enwiki8 example
=> Automatically download owt2

requirements.txt
=> update tensorflow to 2.4.0

configs/gpt3_small.json, gpt_neox/datasets.py
- had to decrease batch size a fair bit
- also cut out generation in the train script as this doesn't use the deepspeed engine, so can cause ooms
but it finally works again haha. I guess one of the tf2 dataloading classes was having some weird interactions with our GPUs. Who really knows.
=> Revert GPT2Dataset back to old working state

kubernetes/public_cluster.sh
Ready to merge @StellaAthena @sdtblck
=> Small patch. Otherwise stops before setting up new service

megatron/global_vars.py, megatron/training.py
Added validation loss and megatron timers to wandb logging
=> Wandb validation loss and megatron timers

megatron/arguments.py, megatron/model/gpt2_model.py, megatron/model/transformer.py, megatron/model/utils.py, megatron/mpu/__init__.py, megatron/mpu/layers.py
Untested currently - will report back w stats
=> Add RMSNorm

kubernetes/deploy_cluster.sh
Ive tested it with both our image `leogao2/gpt-neox:sha-ef55a42` and the base image `atlanticcrypto/cuda-ssh-server:10.2-cudnn`
=> Bug fix: deploy script

configs/eleutherai_cluster.yml, configs/local_setup.yml, configs/pretrain_gpt2.yml, configs/pretrain_gpt2_onebit.yml, kubernetes/k8_spec_ssd-cluster.yml
@sid @StellaAthena 
Suggested save locations for checkpoints. I have also increased disk space so more checkpoints can be saved
=> Checkpoint save location and disk space

Dockerfile, kubernetes/deploy_cluster.sh, kubernetes/k8s_a100_cluster_spec.yml, kubernetes/k8s_cluster_spec.yml, requirements.txt
Plus newer deeperspeed and torch
=> Deploy script for A100s

Dockerfile, README.md, kubernetes/deploy_cluster.sh
Purge pip cache
Reduced from 7.86GB to 4.97GB
=> Make docker image smaller

megatron/model/transformer.py, megatron/mpu/__init__.py, megatron/mpu/initialize.py
pretty sure this should fix it, but unfortunately sparse attn doesn't work with cuda 11.1 anyway, so i have nowhere I can easily test.
=> Sparse attn fix for mp > 1

Dockerfile, requirements.txt
Bump deeperspeed version. Fix sudo bug
=> Bump deeperspeed version. Fix sudo bug

megatron/model/gpt2_model.py, megatron/model/language_model.py
This fixes the wild goose chase you've all been on last night
^ above is the exact same config, before and after this PR's changes
=> fix no weight tying when pp=0

requirements.txt, tools/corpora.py, tools/preprocess_data.py
Now supports:
- Lmd based archive handling (this includes efficient zstd and tar handling)
- No more unpacking compressed files
- Multi-file support
- Vastly simplified dataset class
=> Rewrite data download and tokenization pipeline

megatron/mpu/initialize.py
(necessary for sparse attention in 3D parallel)
=> Fix get_data_parallel_src_rank

.gitignore, megatron/checkpointing.py, megatron/model/transformer.py
This bug was so fucking dumb lol.
To give a brief explainer, checkpoint loading was only working correctly if you'd saved + loaded a checkpoint previously.
Spent a good few days trying to figure out why, and it turns out in 'load_checkpoint' (not save_checkpoint, of course) megatron set a global variable called `checkpoint version`. (https://github.com/EleutherAI/gpt-neox/blob/main/megatron/checkpointing.py#L292) 
`checkpoint version` controls how some layers are transposed in the self attention block. (https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/transformer.py#L300) But since it's only set on load, we *never set this global variable until we load a checkpoint* and therefore after the very first loading from a checkpoint, the way the last dimension is transposed in the …
=> fix checkpointing bug

requirements/requirements.txt, tools/preprocess_data.py
=> remove --split-sentence from preprocess_data.py

megatron/model/gpt2_model.py, megatron/model/transformer.py
So I did a big woops and, since the final linear layer when weight tying was turned off didn't inherit from torch.nn.module, its parameters weren't even getting registered :facepalm: 
This should fix that.
=> [BUGFIX] fix final linear layer

megatron/model/gpt2_model.py
=> fix fineal linear layer w pipe parallel

megatron/data/indexed_dataset.py
Just some comments for someone who wants to figure out, what the memory mapped file format looks like on disk.
=> some comments on indexed_dataset.py

megatron/text_generation_utils.py
@sweinbach 's latest PR accidentally reverted the sampling bugfixes from https://github.com/EleutherAI/gpt-neox/pull/253
this just reverts the reversion :)
=> re-fix https://github.com/EleutherAI/gpt-neox/pull/253

configs/sparse.yml
my bad accidentally pushed a testing config to the refactor-sparse branch
=> Update sparse config to actually do what it says

configs/local_setup.yml, deepy.py, megatron/neox_arguments/neox_args.py, megatron/utils.py
adding parameters for wand_host and wand_project
=> Add wandb params

configs/README.md, configs/eleutherai_cluster.yml, configs/local_setup.yml, megatron/data/gpt2_dataset.py, megatron/logging.py, megatron/model/activations.py, megatron/model/transformer.py, megatron/model/utils.py, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, megatron/training.py, megatron/utils.py, tests/model/test_configs/test_local_setup.yml
Added new feature https://github.com/EleutherAI/gpt-neox/issues/263
=> Added custom train, test and valid data-path functionality

megatron/neox_arguments/arguments.py
forgot to push this final change before i merged the last commit
=> Fix / update data path assertion

megatron/neox_arguments/arguments.py
sorry, need to stop working so late :facepalm:
=> missing bracket oops

.gitignore, configs/eleutherai_cluster.yml, configs/local_setup.yml, megatron/data/blendable_dataset.py, megatron/data/data_utils.py, megatron/data/gpt2_dataset.py, megatron/data/helpers.cpp, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, megatron/training.py, megatron/utils.py, tests/model/test_configs/test_local_setup.yml, tools/corpora.py
Adds the ability to feed in multiple datasets + blend them with weights (see examples in local_setup.yml / eleutherai_cluster.yml
=> Add blended datasets

megatron/model/init_functions.py, megatron/neox_arguments/neox_args.py
In the tradition introduced by kindiana, I named this patch after myself.
=> feat(model): add patched orthogonal init

configs/local_setup.yml, megatron/checkpointing.py, megatron/neox_arguments/neox_args.py, megatron/training.py, requirements/requirements.txt, text_gen_gpt2.py
-  This PR fixes the args validation when loading checkpoints. It was not run (any more).
- unused tracker file is removed
=> Checkpoint validation

megatron/data/blendable_dataset.py, megatron/data/data_utils.py, megatron/data/gpt2_dataset.py, megatron/data/helpers.cpp, megatron/initialize.py, megatron/model/utils.py, megatron/neox_arguments/neox_args.py
adds bigbird + bslongformer sparse attention options
needs deeperspeed commit 24026e5bb37c528a222b8635c46256b1e1825d2e or later
=> Add new sparse attention options

megatron/model/gmlp.py
Adds support for adaptive sequence lengths
=> update GMLP based on lucid's feedback

tools/corpora.py
Apparently my last changes broke a couple things - I actually tested this time lol
=> Fix corpora.py

README.md
Fixes #358 by updating to the latest join link.
=> Update Discord link in README.md

requirements/requirements.txt
=> remove editable flag from deeperspeed install

deepy.py
none of these changes were necessary - and config monster doesn't even exist anymore
=> revert unwanted changes in deepy.py

tools/preprocess_data.py
semaphore is a little too small and slows down tokenizing
=> optimize data preprocessing

megatron/neox_arguments/neox_args.py, megatron/training.py, megatron/utils.py
Sorry, my autoformatter went ham.
Probably not the worst thing. 
Relevant changes are:
- adds a char counter here: https://github.com/EleutherAI/gpt-neox/compare/char_level_ppl?expand=1#diff-b6ee2c1db780b46787ab3a576020f9a12695f3f5cb38ba8badcd5501960e5d22R440
- adds the option to turn on char level ppl here: https://github.com/EleutherAI/gpt-neox/compare/char_level_ppl?expand=1#diff-fefa29324180c69866ca857d29fb03443ef143b9fee5aa5217cd5f5e5ae2b82cR892
- In eval, wraps the data iterator in a char counter that counts the characters and tokens as we iterate through it (needed to do it this way because we don't have access to the deepspeed internals when doing pipe parallel), then uses this info to calculate the char level ppl here: https://github.com/EleutherAI/gpt-neox/compare/char_level_ppl? …
=> Char level ppl

megatron/model/transformer.py, megatron/neox_arguments/neox_args.py
realised just now we're dividing over the model dim in the output layer, vocab dim might (?) be more sensible
=> add parameter that controls how the output layer is parallelized

configs/bnb_small.yml, megatron/model/word_embeddings.py, megatron/neox_arguments/neox_args.py, megatron/training.py, megatron/utils.py
@sdtblck -- Here's the PR with bnb support. I added their StableEmbedding and Adam8bit optimizer.
I've tested basic functionality, but haven't run full training testing. A sample config is in "configs/bnb_small.yml". I can test if you provide instructions, or you can test and let me know the results.
=> Added bitsandbytes Adam optimizer

megatron/model/positional_embeddings.py
Using cached layer past implies a smaller input to the model (only the latest token). Alibi embeddings did not account for that and resulted in unaligned shapes and the second forward pass.
=> fix alibi inference shapes for cached layer_past

megatron/model/positional_embeddings.py
Reverts EleutherAI/gpt-neox#450
Need to test with an alibi trained checkpoint
=> Revert "fix alibi inference shapes for cached layer_past"

megatron/__init__.py, megatron/data/gpt2_dataset.py
Modified the print_rank_0 function to follow "If distributed is initialized print only on rank 0."
=> Remove redundant if-else and fix typos

megatron/model/gpt2_model.py, megatron/mpu/layers.py
=> T5 rpe scale

configs/neox_arguments.md, megatron/neox_arguments/neox_args.py, megatron/tokenizer/tokenizer.py
Hello!
i'm using your repo for GPT-Large training
When i started using your repo, i created russian tokenizer using HF's "tokenizers" library and got stuck by this problem
https://github.com/huggingface/tokenizers/issues/268
Now i'm using SentencePiece tokenizer and doing just fine
I hope this will be useful for languages other than english
Currently i'm asking if this useful at all, so i'll add a little documentation and tests for new class
Thanks in advance!
=> adding SentencePiece Tokenizer

README.md, configs/20B.yml, configs/neox_arguments.md, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, prepare_data.py, tools/corpora.py, tools/preprocess_data.py
don't merge yet, still waiting to fill in a few links :)
=> 20B Release

.pre-commit-config.yaml, README.md, configs/neox_arguments.md, megatron/checkpointing.py, megatron/data/data_utils.py, megatron/data/gpt2_dataset.py, megatron/data/helpers.cpp, megatron/fused_kernels/__init__.py, megatron/fused_kernels/compat.h, megatron/initialize.py, megatron/model/fused_softmax.py, megatron/model/gpt2_model.py, megatron/model/init_functions.py, megatron/model/utils.py, megatron/mpu/cross_entropy.py, megatron/mpu/data.py, megatron/neox_arguments/__init__.py, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, megatron/text_generation_utils.py, megatron/tokenizer/gpt2_tokenization.py, megatron/training.py, megatron/utils.py, tests/neox_args/test_neoxargs_usage.py, tools/inspect_checkpoints.py, tools/merge_mp_partitions.py
add codespell to pre commit and fix few mispells in the code
=> Add codespell

.github/workflows/pull_request.yml, megatron/checkpointing.py, megatron/logging.py, megatron/training.py, megatron/utils.py, requirements/requirements-dev.txt, requirements/requirements.txt, tests/README.md, tests/common.py, tests/model/test_fused_kernels.py, tests/model/test_model_checkpoint.py, tests/model/test_model_generation.py, tests/model/test_model_train.py, tests/neox_args/test_neoxargs_commandline.py, tests/neox_args/test_neoxargs_usage.py, train.py
Add changes to run most of the tests again. The parallel ones seem require multi gpu environment that I don't have available right now
=> Update GitHub framework to run on GPUs

.github/workflows/pull_request.yml
Resolves outstanding issues from #595, scope the `git add` call, install missing dependencies, and _temporarily_ remove two init files as they include unnecessary code.
=> Resolve whitespace issue that breaks the pull_request workflow

README.md, configs/neox_arguments.md, tools/merge20b.py
Simple script for merging 20B to run on 1 GPU.
=> Merge-script for 1 GPU 20b, and minimal

configs/neox_arguments.md, tools/merge20b.py
Not sure why I commented this out in the first place
=> Uncomment merge code

tests/neox_args/test_neoxargs_usage.py
Reverts EleutherAI/gpt-neox#639
=> Revert "[WIP] Fix Unit Tests"

configs/small.yml, megatron/neox_arguments/arguments.py, tests/neox_args/test_neoxargs_commandline.py
=> Resolve `hostfile` CLI Param Overwriting Config Value

configs/neox_arguments.md, megatron/neox_arguments/neox_args.py, megatron/text_generation_utils.py
=> Add Support for Returning Logits for Generated Tokens

README.md, configs/neox_arguments.md, configs/small.yml, eval_tasks/eval_adapter.py, megatron/initialize.py, megatron/model/word_embeddings.py, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, megatron/text_generation_utils.py, requirements/requirements.txt, tests/neox_args/test_neoxargs_commandline.py, tests/neox_args/test_neoxargs_usage.py
Reverts EleutherAI/gpt-neox#673
=> Revert "Deepspeed main"

README.md
Follow up to commit 0709327633973cfc656f5a12e3435cfb508e90e7
=> Fix link to download 20B vocab

.github/workflows/cpu_ci.yml, configs/cpu_mock_config.yml, tests/neox_args/test_neoxargs_commandline.py, tests/neox_args/test_neoxargs_load.py
All the CPU tests now succeed locally for me on my GPU-less dev machine.
=> Fix Failing CPU Tests & Properly Configure CPU Continues Integration

configs/1-3B.yml, configs/125M.yml, configs/13B.yml, configs/175B.yml, configs/19M.yml, configs/2-7B.yml, configs/20B.yml, configs/350M.yml, configs/49M.yml, configs/6-7B.yml, configs/760M.yml, configs/800M.yml, configs/README.md, configs/bf16_125M.yml, configs/bnb_125M.yml, configs/neox_arguments.md, configs/slurm_125M.yml, megatron/neox_arguments/arguments.py, tests/test_configs/test_train_base.yml
Fixes https://github.com/EleutherAI/gpt-neox/issues/469 and applies https://github.com/EleutherAI/gpt-neox/pull/665 to feature configs
=> Deprecate cpu_offload zero_optimization Option

README.md, configs/neox_arguments.md
@StellaAthena this is ready for review!
=> Amend readme w/ FIM and HF conversion

configs/neox_arguments.md, megatron/neox_arguments/neox_args.py, megatron/tokenizer/tokenizer.py, prepare_data.py, requirements/requirements.txt, tools/preprocess_data.py
This PR adds a `tiktoken` tokenizer (https://github.com/openai/tiktoken) to NeoX.
=> Add tiktoken Tokenizer support

README.md, configs/neox_arguments.md
WIP towards revamping the Quick Start instructions to actually be a quick start
=> Quick Start Revamp

README.md, configs/neox_arguments.md
Reverts EleutherAI/gpt-neox#747
=> Revert "Quick Start Revamp"

README-MUP.md, configs/neox_arguments.md, megatron/data/data_utils.py, megatron/data/gpt2_dataset.py, megatron/learning_rates.py, megatron/model/flash_attention.py, megatron/model/gpt2_model.py, megatron/model/init_functions.py, megatron/model/transformer.py, megatron/mpu/layers.py, megatron/mup_substitute.py, megatron/tokenizer/tokenizer.py, megatron/training.py, requirements/requirements.txt, tools/corpora.py
We've accrued a lot of formatting debt in recent commits. This PR just applies all the pre-commit checks and brings formatting back into shape.
No functional changes were made.
=> Formatting Cleanup

configs/neox_arguments.md, tools/convert_to_hf.py, tools/upload.py
Closes #798 .
Checkpoint now converts on GPU if CUDA available, stays on CPU if not. We could change this behavior to be on CPU by default if desired.
Model checkpoints are explicitly cast + saved in half() precision if using FP16 during training in the YAML, and saved in 32 bit precision if not. 
cc @Quentin-Anthony
=> Minor Usability Fixes for HF Conversion

megatron/logging.py
This PR aims to improve the type hints of the logging submodule.
=> feat(logging): improve typing

configs/neox_arguments.md, megatron/model/transformer.py, megatron/neox_arguments/neox_args.py
See https://github.com/EleutherAI/gpt-neox/issues/905
This is just a hotfix. Needs shape checking or a rework to fix the underlying issue.
=> Disable row-parallelism for now

megatron/model/transformer.py
Thanks for maintaining this great open source library!  Quick fix for first contrib: fixing flash attention which is currently broken for micro batch size > 1 due to unstored reshape of `query_layer`
=> Fix flash attention

configs/neox_arguments.md, megatron/learning_rates.py
Fixed final value of cosine decay lr so that it is equal to min lr
=> Fixed final value of cosine decay lr

configs/neox_arguments.md, requirements/requirements.txt, tools/corpora.py
Bumps `transformers` version to fix #1013 .
=> Bump transformers version and update enwik8 link

configs/neox_arguments.md, megatron/learning_rates.py
Mirrors the fixes in https://github.com/EleutherAI/gpt-neox/pull/1039 to fix the final iter for exponential lr decay
=> Fix final value of exponential decay lr

README.md, configs/neox_arguments.md
For SLURM includes a sample hostfile-creation script and a barebones sbatch script.
=> Add section to the README detailing how to start distributed jobs

CITATION.cff, README.md, configs/neox_arguments.md
Added @dashstander, @zphang, @haileyschoelkopf, @curt-tigges, @bentherien
=> Update citation list

configs/neox_arguments.md, megatron/neox_arguments/neox_args.py
Fixes the auto deletion of Lion optimizer documentation.
=> fix lion optimizer documentation

megatron/fused_kernels/fused_rotary_positional_embedding.cpp, megatron/fused_kernels/fused_rotary_positional_embedding.h
Ports the updates introduced in https://github.com/NVIDIA/apex/pull/1751
=> Avoid .contiguous()

.github/workflows/pull_request.yml, Dockerfile, requirements/requirements.txt
- Add missing jinja2 dep
- Fix Dockerfile
- Ensure Dockerfile builds in CI
=> Fix install, Dockerfile, CI

configs/pythia/14M.yml, configs/pythia/31M.yml
Haven't tested them, copied directly from [here](https://github.com/EleutherAI/pythia/tree/e1207509b11775bf658ba23c859883f7d3e6e7c1/models) which is the latest Pythia commit.
=> Add pythia 14M and 31M configs

configs/pythia/1-4B.yml, configs/pythia/14M.yml, configs/pythia/160M.yml, configs/pythia/31M.yml, configs/pythia/410M.yml, configs/pythia/70M.yml
=> Remove gas from Pythia configs

megatron/model/transformer.py
=> Fix moe_loss in gpt_j_residual path

megatron/data/data_utils.py
Related to https://github.com/mosaicml/streaming/issues/573
=> [streaming_ds branch] Clean shared memory before training to fix hanging bug

README.md
Correcting a small but annoying typo for beginners
=> ENH Small typo in the README

.github/workflows/cpu_ci_on_pr.yml, configs/neox_arguments.md
Credit to @ma-pineda for instrumenting the dockerfile in the CI test and the test structure.
This workflow will run the CPU tests on changes to megatron/* files.
=> making PR triggered CPU test for changes to megatron

.github/workflows/cpu_ci_dispatch.yml, .github/workflows/cpu_ci_on_pr.yml, configs/neox_arguments.md, tests/cpu_tests/action.yml, tests/cpu_tests/docker-compose.yml
Updates to CPU CI tests:
- Abstracting CPU CI to composite file for reusability
- Added workflow_dispatch trigger to run manually
- Added pull_request trigger to activate on (megatron) changes in PR
- Calling CI on branches older than this may fail if the tweaked docker-compose.yml file is missing
=> Jaimemcc intel/ci composite cpu tests

configs/neox_arguments.md
fixes the failed document updating from #1192, just forces the document update to run again.
=> Run document update again

configs/neox_arguments.md, megatron/neox_arguments/arguments.py
Allow pipeline parallelism for rwkv.
=> Rwkv pipeline parallelism

README.md, megatron/fused_kernels/__init__.py, tests/model/test_fused_kernels.py
=> fixed fused_rope naming in JIT + Readme

.github/workflows/pull_request.yml, configs/neox_arguments.md
WIP PR - opening to trigger GHA.
=> Change python invocation syntax

megatron/model/transformer.py
Was introduced in https://github.com/EleutherAI/gpt-neox/pull/1212
@jahatef -- FYI
=> Hotfix Activation Typo

README.md, configs/125M.yml, configs/local_setup.yml, eval.py, megatron/logging.py, megatron/model/transformer.py, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, megatron/training.py, megatron/utils.py, requirements/requirements-comet.txt, tools/ckpts/convert_hf_to_sequential.py, tools/datasets/preprocess_data_with_chat_template.py, train.py
Introduces a new [Comet](https://comet.com) integration.
=> Comet integration

megatron/model/transformer.py, megatron/neox_arguments/arguments.py, megatron/training.py, tools/datasets/preprocess_data_with_chat_template.py
-Adds clear messages when trying to use ZeRO 2/3 pipeline or model parallel.
-Update is_pipe_parallel comment
=> Add more informative checks for ZeRO incompatibility.

configs/llama/13B.yml, configs/llama/30B.yml, configs/llama/65B.yml, configs/llama/7B.yml, configs/llama/train_config.yml, configs/llama2/13B.yml, configs/llama2/70B.yml, configs/llama2/7B.yml, configs/llama2/codellama_34B.yml, configs/llama2/codellama_7B.yml, configs/llemma/34B.yml, configs/llemma/7B.yml, configs/mistral/7B.yml, megatron/model/megablocks_utils.py, megatron/model/transformer.py, megatron/model/utils.py, megatron/neox_arguments/arguments.py, megatron/neox_arguments/neox_args.py, tests/model/test_model_train.py, tools/ckpts/convert_hf_llama_to_neox.py, tools/ckpts/convert_neox_to_hf.py
Quick hotfix to support llama models
- MLP Bias arg
- Multiple of arg (should probably just remove the helpful 2*ff_dim / 3 thing...)
- converter update
Still need to make the neox -> llama converter but this lets me train
=> Hotfix llama models

configs/neox_arguments.md, megatron/fused_kernels/type_shim.h
I believe we're out of github runner credits so this isn't automatic anymore.
FYI -- @jahatef
=> update args docs

megatron/model/transformer.py
fix a GQA issue (#1314)
- do not create a fake head dim and split the 'mixed_x_layer' into QKV layers directly.
=> fix a GQA issue (#1314)

megatron/model/norms.py, megatron/neox_arguments/neox_args.py
Addresses issues in #1332
https://github.com/EleutherAI/gpt-neox/pull/1332#discussion_r1957218573
WandB profile on a 125M model: https://api.wandb.ai/links/shetano-personal/j6bbm4c9
=> Creating NonParametricLayernorm class
